language: python
python:
  - "2.7"
  - "3.5"
stages:
  - lint
  - test
install: pip install tox tox-travis
jobs:
  include:
    - stage: lint
      script: tox -e lint
      python: "3.5"
script: tox
